import feedparser
import os
import datetime
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

FEEDS = {
    "dbt": "https://www.getdbt.com/blog/rss.xml",
    "Databricks": "https://www.databricks.com/blog/feed",
    "Airbyte": "https://airbyte.com/blog/rss.xml",
    "Snowflake": "https://www.snowflake.com/blog/feed/"
}

def fetch_weekly_news():
    digest_input = []
    now = datetime.datetime.now(datetime.timezone.utc)
    for source, url in FEEDS.items():
        feed = feedparser.parse(url)
        for entry in feed.entries:
            try:
                pub_date = datetime.datetime(*entry.published_parsed[:6], tzinfo=datetime.timezone.utc)
                if (now - pub_date).days <= 7:
                    digest_input.append(f"Source: {source} | Title: {entry.title} | Link: {entry.link}")
            except: continue
    return "\n".join(digest_input)

def generate_html_content(news_text):
    prompt = f"""
    Summarize these data news items into a beautiful HTML news digest.
    Use Tailwind CSS classes for styling. 
    Wrap the content in a <div class="max-w-4xl mx-auto p-6 bg-white shadow-lg rounded-lg">.
    Include: 
    1. A header 'Weekly Data Insights'.
    2. Sections for each major update with 'Sentiment' analysis.
    3. Use cards for each news item.
    4. Make links look like buttons.
    
    NEWS DATA:
    {news_text}
    """
    
    completion = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return completion.choices[0].message.content

def save_as_html_file(ai_content):
    full_html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Data Industry Digest</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>
            body {{ background-color: #f3f4f6; font-family: 'Inter', sans-serif; }}
        </style>
    </head>
    <body class="py-10">
        {ai_content}
        <footer class="text-center text-gray-400 mt-8 text-sm">
            Updated on {datetime.date.today().strftime('%B %d, %Y')} | Generated by AI
        </footer>
    </body>
    </html>
    """
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(full_html)

if __name__ == "__main__":
    news = fetch_weekly_news()
    if news:
        content = generate_html_content(news)
        save_as_html_file(content)
        print("index.html created!")